name = "pijori"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "582c11f9-f3a1-4114-8a3c-e84a3742cd78"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
